import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MaxWidthWrapper from "@/components/landingPage/MaxWidthWrapper";
import Navbar from "@/components/mainDashboard/Navbar";
import SideNav from "@/components/mainDashboard/SideNav";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-white text-black", inter.className)}>
        <main className="flex min-h-screen">
          <SideNav />
          <div className="w-full">
            <MaxWidthWrapper>
              <Navbar />
            </MaxWidthWrapper>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
